use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Root configuration struct for `.riceguard.yaml`.
///
/// Generated by `rice-guard init` and loaded at the start of every scan/fix.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiceGuardConfig {
    /// Schema version — always `"1"` for this release.
    pub version: String,

    /// Project identity and language metadata.
    pub project: ProjectConfig,

    /// Scanner enable/config section.
    #[serde(default)]
    pub scanners: ScannersConfig,

    /// Fixer enable/config section.
    #[serde(default)]
    pub fixers: FixersConfig,

    /// File include/exclude glob patterns (INIT-13).
    #[serde(default)]
    pub filters: FiltersConfig,

    /// Tool availability map (populated by `init`).
    #[serde(default)]
    pub tools: ToolsConfig,

    /// Output format settings.
    #[serde(default)]
    pub output: OutputConfig,

    /// Pre-commit hook configuration.
    #[serde(default)]
    pub hooks: HooksConfig,

    /// CI integration configuration.
    #[serde(default)]
    pub ci: CiConfig,
}

impl Default for RiceGuardConfig {
    fn default() -> Self {
        Self {
            version: "1".to_string(),
            project: ProjectConfig {
                name: String::new(),
                languages: Vec::new(),
                topology: Topology::default(),
                architecture: Architecture::default(),
            },
            scanners: ScannersConfig::default(),
            fixers: FixersConfig::default(),
            filters: FiltersConfig::default(),
            tools: ToolsConfig::default(),
            output: OutputConfig::default(),
            hooks: HooksConfig::default(),
            ci: CiConfig::default(),
        }
    }
}

// ── Project ─────────────────────────────────────────────────────────────────

/// Project identity and detected language metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectConfig {
    /// Short project name (e.g., "my-app").
    pub name: String,

    /// Detected languages (e.g., ["rust", "typescript"]).
    #[serde(default)]
    pub languages: Vec<String>,

    /// Project topology.
    #[serde(default)]
    pub topology: Topology,

    /// Architecture style, if known.
    #[serde(default)]
    pub architecture: Architecture,
}

/// Deployment / repository topology.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "lowercase")]
pub enum Topology {
    Monorepo,
    #[default]
    Monolith,
    Library,
    Cli,
    Mobile,
}

/// Architecture pattern in use, if any.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "lowercase")]
pub enum Architecture {
    Clean,
    Hexagonal,
    Mvc,
    #[default]
    None,
}

// ── Scanners ─────────────────────────────────────────────────────────────────

/// Top-level scanner configuration block.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ScannersConfig {
    #[serde(default)]
    pub semgrep: SemgrepConfig,

    #[serde(default)]
    pub trivy: TrivyConfig,

    #[serde(rename = "ast-grep", default)]
    pub ast_grep: AstGrepConfig,

    #[serde(default)]
    pub gitleaks: GitleaksConfig,

    #[serde(default)]
    pub jscpd: JscpdConfig,

    #[serde(default)]
    pub scc: SccConfig,

    #[serde(default)]
    pub sonarqube: SonarqubeConfig,
}

/// Semgrep scanner configuration.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SemgrepConfig {
    pub enabled: bool,
    #[serde(default)]
    pub rulesets: Vec<String>,
}

/// Trivy scanner configuration.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct TrivyConfig {
    pub enabled: bool,
    #[serde(default)]
    pub scanners: Vec<String>,
}

/// ast-grep scanner configuration.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AstGrepConfig {
    pub enabled: bool,
    #[serde(default)]
    pub rules: String,
}

/// Gitleaks git-history secrets scanner configuration.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct GitleaksConfig {
    pub enabled: bool,
}

/// jscpd code-duplication scanner configuration.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct JscpdConfig {
    pub enabled: bool,
    #[serde(default)]
    pub threshold: u32,
}

/// scc lines-of-code / complexity scanner configuration.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SccConfig {
    pub enabled: bool,
}

/// Optional SonarQube integration configuration.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SonarqubeConfig {
    pub enabled: bool,
    #[serde(default)]
    pub host: String,
    /// SonarQube user token. Prefer `SONARQUBE_TOKEN` env var over storing here.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// SonarQube project key. Auto-derived from directory name if absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_key: Option<String>,
}

// ── Fixers ───────────────────────────────────────────────────────────────────

/// Top-level fixer pipeline configuration.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct FixersConfig {
    /// Run all formatters (rustfmt, gofumpt, ruff format, etc.).
    #[serde(default = "default_true")]
    pub formatters: bool,

    /// Run linter auto-fix (clippy --fix, golangci-lint --fix, etc.).
    #[serde(default = "default_true")]
    pub linters: bool,

    /// Run semgrep --autofix for pattern-based security fixes.
    #[serde(default = "default_true")]
    pub security: bool,

    /// Run embedded ast-grep fix rules.
    #[serde(default = "default_true")]
    pub ast: bool,

    /// Run dependency update commands (cargo update, npm audit fix, etc.).
    #[serde(default = "default_true")]
    pub deps: bool,

    /// Allow unsafe linter fixes (opt-in).
    #[serde(default)]
    pub r#unsafe: bool,
}

fn default_true() -> bool {
    true
}

// ── Filters (INIT-13) ────────────────────────────────────────────────────────

/// File filtering configuration (INIT-13).
///
/// Controls which files are included in / excluded from scanning and fixing.
/// Empty `include` means include everything; `exclude` patterns are always applied.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct FiltersConfig {
    /// Glob patterns for files to include. Empty = include everything.
    ///
    /// Example: `["src/**", "lib/**"]`
    #[serde(default)]
    pub include: Vec<String>,

    /// Glob patterns for files to exclude (generated code, vendor dirs, etc.).
    ///
    /// Example: `["vendor/", "node_modules/", "*.generated.*"]`
    #[serde(default)]
    pub exclude: Vec<String>,

    /// When `true`, patterns from `.gitignore` are loaded into the ignore engine
    /// in addition to `.riceguardignore` / `.rgignore`.
    ///
    /// Defaults to `false` — rice-guard has its own ignore files and should not
    /// silently inherit git's exclusions unless the user opts in.
    #[serde(default)]
    pub respect_gitignore: bool,
}

impl FiltersConfig {
    /// Returns the default exclude patterns used when generating a new config.
    pub fn default_excludes() -> Vec<String> {
        vec![
            "vendor/".into(),
            "node_modules/".into(),
            "target/".into(),
            ".git/".into(),
            "*.generated.*".into(),
            "dist/".into(),
        ]
    }
}

// ── Tools ────────────────────────────────────────────────────────────────────

/// Tool availability map, populated by `rice-guard init`.
///
/// `scanners` maps scanner name -> available (bool).
/// `fixers` maps language -> (tool_name -> available).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ToolsConfig {
    /// Scanner availability: `{ "semgrep": true, "trivy": false, ... }`
    #[serde(default)]
    pub scanners: HashMap<String, bool>,

    /// Fixer availability per language: `{ "rust": { "rustfmt": true }, ... }`
    #[serde(default)]
    pub fixers: HashMap<String, HashMap<String, bool>>,
}

// ── Output ───────────────────────────────────────────────────────────────────

/// Output format and filtering settings.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutputConfig {
    /// Output format: `"json"`, `"text"`, or `"sarif"`.
    #[serde(default = "default_format")]
    pub format: String,

    /// Minimum severity to include in reports: `"error"`, `"warning"`, `"info"`.
    #[serde(default = "default_severity_threshold")]
    pub severity_threshold: String,

    /// Whether to embed code evidence in every issue.
    #[serde(default = "default_true")]
    pub include_evidence: bool,
}

impl Default for OutputConfig {
    fn default() -> Self {
        Self {
            format: default_format(),
            severity_threshold: default_severity_threshold(),
            include_evidence: true,
        }
    }
}

fn default_format() -> String {
    "json".into()
}

fn default_severity_threshold() -> String {
    "warning".into()
}

// ── Hooks ────────────────────────────────────────────────────────────────────

/// Pre-commit hook integration settings.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "kebab-case")]
pub struct HooksConfig {
    #[serde(default)]
    pub pre_commit: PreCommitConfig,
}

/// Pre-commit hook configuration (lefthook or husky).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PreCommitConfig {
    pub enabled: bool,
    #[serde(default)]
    pub manager: String,
    #[serde(default)]
    pub checks: Vec<String>,
}

// ── CI ───────────────────────────────────────────────────────────────────────

/// CI integration settings.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CiConfig {
    /// CI provider: `"github"`, `"gitlab"`, `"none"`.
    #[serde(default)]
    pub provider: String,

    /// Only report issues on changed files (hold-the-line mode).
    #[serde(default)]
    pub diff_only: bool,
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn minimal_config() -> RiceGuardConfig {
        RiceGuardConfig {
            version: "1".into(),
            project: ProjectConfig {
                name: "test-project".into(),
                languages: vec!["rust".into()],
                topology: Topology::Cli,
                architecture: Architecture::None,
            },
            scanners: ScannersConfig {
                semgrep: SemgrepConfig {
                    enabled: true,
                    rulesets: vec!["p/default".into()],
                },
                ..Default::default()
            },
            fixers: FixersConfig {
                formatters: true,
                linters: true,
                security: false,
                ast: false,
                deps: true,
                r#unsafe: false,
            },
            filters: FiltersConfig {
                include: vec![],
                exclude: FiltersConfig::default_excludes(),
                respect_gitignore: false,
            },
            tools: ToolsConfig::default(),
            output: OutputConfig::default(),
            hooks: HooksConfig::default(),
            ci: CiConfig {
                provider: "github".into(),
                diff_only: false,
            },
        }
    }

    #[test]
    fn roundtrip() {
        let config = minimal_config();
        let yaml = serde_yaml_ng::to_string(&config).expect("serialize to YAML");
        let restored: RiceGuardConfig =
            serde_yaml_ng::from_str(&yaml).expect("deserialize from YAML");

        // Identity checks on key fields
        assert_eq!(config.version, restored.version);
        assert_eq!(config.project.name, restored.project.name);
        assert_eq!(config.project.topology, restored.project.topology);
        assert_eq!(config.project.architecture, restored.project.architecture);
        assert_eq!(
            config.scanners.semgrep.enabled,
            restored.scanners.semgrep.enabled
        );
        assert_eq!(
            config.scanners.semgrep.rulesets,
            restored.scanners.semgrep.rulesets
        );
        assert_eq!(config.fixers.formatters, restored.fixers.formatters);
        assert_eq!(config.fixers.r#unsafe, restored.fixers.r#unsafe);
        assert_eq!(config.filters.include, restored.filters.include);
        assert_eq!(config.filters.exclude, restored.filters.exclude);
    }

    #[test]
    fn filters_config_has_include_and_exclude() {
        let config = minimal_config();
        assert!(
            config.filters.include.is_empty(),
            "default include should be empty (include all)"
        );
        assert!(
            config.filters.exclude.contains(&"vendor/".to_string()),
            "default exclude should contain vendor/"
        );
        assert!(
            config
                .filters
                .exclude
                .contains(&"node_modules/".to_string()),
            "default exclude should contain node_modules/"
        );
        assert!(
            config.filters.exclude.contains(&"target/".to_string()),
            "default exclude should contain target/"
        );
    }

    #[test]
    fn filters_roundtrip() {
        let config = minimal_config();
        let yaml = serde_yaml_ng::to_string(&config).expect("serialize to YAML");
        let restored: RiceGuardConfig =
            serde_yaml_ng::from_str(&yaml).expect("deserialize from YAML");
        assert_eq!(config.filters.exclude, restored.filters.exclude);
        assert_eq!(config.filters.include, restored.filters.include);
    }

    #[test]
    fn respect_gitignore_defaults_to_false() {
        let config = minimal_config();
        assert!(
            !config.filters.respect_gitignore,
            "respect_gitignore should default to false"
        );
    }

    #[test]
    fn respect_gitignore_roundtrips_through_yaml() {
        let mut config = minimal_config();
        config.filters.respect_gitignore = true;
        let yaml = serde_yaml_ng::to_string(&config).expect("serialize to YAML");
        let restored: RiceGuardConfig =
            serde_yaml_ng::from_str(&yaml).expect("deserialize from YAML");
        assert!(
            restored.filters.respect_gitignore,
            "respect_gitignore=true should survive YAML round-trip"
        );

        // Also test false round-trips correctly
        let mut config2 = minimal_config();
        config2.filters.respect_gitignore = false;
        let yaml2 = serde_yaml_ng::to_string(&config2).expect("serialize to YAML");
        let restored2: RiceGuardConfig =
            serde_yaml_ng::from_str(&yaml2).expect("deserialize from YAML");
        assert!(
            !restored2.filters.respect_gitignore,
            "respect_gitignore=false should survive YAML round-trip"
        );
    }

    #[test]
    fn deserialize_minimal_yaml() {
        let yaml = r#"
version: "1"
project:
  name: my-app
  languages: [rust]
  topology: cli
  architecture: none
"#;
        let config: RiceGuardConfig = serde_yaml_ng::from_str(yaml).expect("parse minimal yaml");
        assert_eq!(config.version, "1");
        assert_eq!(config.project.name, "my-app");
        assert_eq!(config.project.topology, Topology::Cli);
    }
}
