//! MCP server implementation using rmcp's macro-based tool router.
//!
//! `RGuardMcpServer` implements all 9 MCP tools that expose riceGuard's
//! scan and fix pipeline to Claude Code / Cursor via stdio JSON-RPC.
use std::path::{Path, PathBuf};

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    tool, tool_handler, tool_router, ServerHandler,
};
use serde::Serialize;

use crate::mcp::tools::*;

// ─── Helper ──────────────────────────────────────────────────────────────────

/// Serialize `value` into a [`CallToolResult`] with a single text content item.
fn ok<T: Serialize>(value: &T) -> Result<CallToolResult, rmcp::ErrorData> {
    let json = serde_json::to_string(value)
        .map_err(|e| rmcp::ErrorData::internal_error(format!("serialize error: {e}"), None))?;
    Ok(CallToolResult::success(vec![Content::text(json)]))
}

/// Find the latest timestamped reports directory for `project_path`.
///
/// Reports are written to `<project_path>/reports/<timestamp>/`. Returns the
/// most recently modified sub-directory, or an error if none exists.
fn latest_report_dir(project_path: &str) -> anyhow::Result<PathBuf> {
    let reports_root = Path::new(project_path).join("reports");
    if !reports_root.exists() {
        anyhow::bail!(
            "No reports directory found at '{}'. Run `rguard scan {}` first.",
            reports_root.display(),
            project_path
        );
    }

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&reports_root)?
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|t| t.is_dir()).unwrap_or(false))
        .filter(|e| e.file_name() != "latest")
        .map(|e| e.path())
        .collect();

    entries.sort_by_key(|p| {
        p.metadata()
            .and_then(|m| m.modified())
            .unwrap_or(std::time::SystemTime::UNIX_EPOCH)
    });

    entries.into_iter().last().ok_or_else(|| {
        anyhow::anyhow!(
            "No scan results found under '{}'. Run `rguard scan {}` first.",
            reports_root.display(),
            project_path
        )
    })
}

/// Read and deserialize a JSON file.
fn read_json<T: serde::de::DeserializeOwned>(path: &Path) -> anyhow::Result<T> {
    let text = std::fs::read_to_string(path)
        .map_err(|e| anyhow::anyhow!("Cannot read '{}': {e}", path.display()))?;
    serde_json::from_str(&text)
        .map_err(|e| anyhow::anyhow!("Cannot parse '{}': {e}", path.display()))
}

/// Deserialize the issues array from an issues.json value.
///
/// issues.json is wrapped as `{ "schema_version": "1.0", "issues": [...] }`.
fn issues_from_value(
    wrapper: serde_json::Value,
) -> Result<Vec<rguard_core::issue::Issue>, rmcp::ErrorData> {
    let issues_val = wrapper.get("issues").cloned().unwrap_or(wrapper.clone());
    serde_json::from_value(issues_val)
        .map_err(|e| rmcp::ErrorData::internal_error(format!("Parse issues.json: {e}"), None))
}

// ─── Server struct ────────────────────────────────────────────────────────────

/// MCP server that exposes riceGuard's scan and fix pipeline as 9 tools.
///
/// Designed for use with Claude Code / Cursor via stdio JSON-RPC transport.
/// All tracing output goes to stderr — stdout is reserved for the MCP protocol.
#[derive(Debug, Clone)]
pub struct RGuardMcpServer {
    /// Cached [`ToolRouter`] generated by the `#[tool_router]` macro.
    pub tool_router: ToolRouter<Self>,
    /// Working directory when the server was started.
    pub working_dir: PathBuf,
}

// ─── Tool implementations ─────────────────────────────────────────────────────

#[tool_router]
impl RGuardMcpServer {
    /// Construct the server, initializing the tool router.
    pub fn new(working_dir: PathBuf) -> Self {
        Self {
            tool_router: Self::tool_router(),
            working_dir,
        }
    }

    // ── scan_project ──────────────────────────────────────────────────────────

    #[tool(
        description = "Scan a project for code quality, security, and duplication issues. \
        Returns a JSON summary with issue counts by severity and category. \
        After scanning, call get_issues to retrieve individual findings with code evidence. \
        Supported modes: 'full' (all scanners), 'quick' (fast subset), 'security' (security focus)."
    )]
    async fn scan_project(
        &self,
        Parameters(p): Parameters<ScanProjectParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        use rguard_core::{
            config,
            issue::IssueBuilder,
            output::OutputWriter,
            registry::loader::load_scanner_descriptors,
            scanner::{OutputDir, ScanMode, ScannerEngine},
        };

        let project_root = PathBuf::from(&p.path);
        let config_path = project_root.join(".rguard.yaml");
        let cfg = config::load(&config_path).map_err(|e| {
            rmcp::ErrorData::internal_error(format!("Config load failed: {e}"), None)
        })?;

        let mode = match p.mode.as_deref().unwrap_or("full") {
            "quick" => ScanMode::Quick,
            "security" => ScanMode::Security,
            _ => ScanMode::Full,
        };

        let project_name = cfg.project.name.clone();
        let output_dir = OutputDir::new(&project_name, "reports").map_err(|e| {
            rmcp::ErrorData::internal_error(format!("Output dir creation failed: {e}"), None)
        })?;

        let descriptors = load_scanner_descriptors(&project_root)
            .map_err(|e| rmcp::ErrorData::internal_error(format!("Descriptor load: {e}"), None))?;

        let engine = ScannerEngine::new(descriptors, cfg.clone());
        let report = engine
            .run(&project_root, mode, &output_dir)
            .await
            .map_err(|e| rmcp::ErrorData::internal_error(format!("Scan failed: {e}"), None))?;

        // build_batch returns Vec<Issue> directly (infallible)
        let issues = IssueBuilder::build_batch(&report.findings, &project_root, &[]);

        let now = epoch_timestamp();
        let summary = OutputWriter::build_summary(&issues, &p.path, &now, vec![], 0);

        let writer = OutputWriter::new(output_dir.path());
        writer
            .write_all(&issues, &summary)
            .map_err(|e| rmcp::ErrorData::internal_error(format!("Write output: {e}"), None))?;

        ok(&summary)
    }

    // ── get_issues ────────────────────────────────────────────────────────────

    #[tool(
        description = "Get all issues from the most recent scan of the given project path. \
        Issues are sorted by WSJF priority score (highest first). Each issue includes \
        pre-embedded code evidence (matched_code, context_before, context_after, \
        enclosing_function) so you can fix it without reading source files."
    )]
    async fn get_issues(
        &self,
        Parameters(p): Parameters<GetIssuesParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        let dir = latest_report_dir(&p.path)
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;

        let wrapper: serde_json::Value = read_json(&dir.join("issues.json"))
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;

        let mut issues = issues_from_value(wrapper)?;

        if let Some(ref sev) = p.severity {
            issues.retain(|i| i.severity == *sev);
        }

        if let Some(limit) = p.limit {
            issues.truncate(limit);
        }

        ok(&issues)
    }

    // ── get_issue ─────────────────────────────────────────────────────────────

    #[tool(description = "Get a single issue by its fingerprint ID. \
        Returns the full Issue object including code evidence. \
        Returns an error if the ID is not found in the most recent scan.")]
    async fn get_issue(
        &self,
        Parameters(p): Parameters<GetIssueParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        let dir = latest_report_dir(&p.path)
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;

        let wrapper: serde_json::Value = read_json(&dir.join("issues.json"))
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;

        let issues = issues_from_value(wrapper)?;

        let issue = issues.into_iter().find(|i| i.id == p.id).ok_or_else(|| {
            rmcp::ErrorData::invalid_params(
                format!(
                    "Issue '{}' not found in most recent scan of '{}'",
                    p.id, p.path
                ),
                None,
            )
        })?;

        ok(&issue)
    }

    // ── fix_all ───────────────────────────────────────────────────────────────

    #[tool(description = "Apply all deterministic fixers to the project. \
        Runs in order: formatters -> linters -> security -> ast -> deps -> imports. \
        Missing tools are skipped with warnings. \
        Optional: filter by category to run only one stage. \
        Returns a fix report documenting what was fixed, skipped, and failed.")]
    async fn fix_all(
        &self,
        Parameters(p): Parameters<FixAllParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        let report = run_fixer(&p.path, p.category.as_deref(), false, p.unsafe_fixes, None)
            .await
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;
        ok(&report)
    }

    // ── fix_issue ─────────────────────────────────────────────────────────────

    #[tool(description = "Fix a specific issue by its fingerprint ID. \
        Looks up the auto_fix_tool from the issue's fix metadata and runs only that fixer. \
        Returns a fix report for the targeted issue.")]
    async fn fix_issue(
        &self,
        Parameters(p): Parameters<FixIssueParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        let report = run_fixer(&p.path, None, false, false, Some(vec![p.id]))
            .await
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;
        ok(&report)
    }

    // ── fix_preview ───────────────────────────────────────────────────────────

    #[tool(
        description = "Preview all fixes that would be applied without modifying any files. \
        Equivalent to running fix with --dry-run. \
        Returns the same fix report structure as fix_all but with dry_run=true."
    )]
    async fn fix_preview(
        &self,
        Parameters(p): Parameters<FixPreviewParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        let report = run_fixer(&p.path, p.category.as_deref(), true, false, None)
            .await
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;
        ok(&report)
    }

    // ── get_fix_report ────────────────────────────────────────────────────────

    #[tool(description = "Get the fix report from the most recent fix run. \
        Shows what was fixed, what was skipped, and what failed per stage. \
        Returns an error if no fix has been run yet.")]
    async fn get_fix_report(
        &self,
        Parameters(p): Parameters<GetFixReportParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        let dir = latest_report_dir(&p.path)
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;

        let fix_report_path = dir.join("fix-report.json");
        if !fix_report_path.exists() {
            return Err(rmcp::ErrorData::internal_error(
                format!(
                    "No fix report found at '{}'. Run `rguard fix {}` first.",
                    fix_report_path.display(),
                    p.path
                ),
                None,
            ));
        }

        let raw = std::fs::read_to_string(&fix_report_path).map_err(|e| {
            rmcp::ErrorData::internal_error(format!("Read fix-report.json: {e}"), None)
        })?;

        Ok(CallToolResult::success(vec![Content::text(raw)]))
    }

    // ── verify_fix ────────────────────────────────────────────────────────────

    #[tool(description = "Verify that a previously fixed issue is resolved. \
        Reruns the verification command from the issue's verification.rerun_command field. \
        Returns true if the fix is confirmed or false if the issue persists.")]
    async fn verify_fix(
        &self,
        Parameters(p): Parameters<VerifyFixParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        let dir = latest_report_dir(&p.path)
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;

        let wrapper: serde_json::Value = read_json(&dir.join("issues.json"))
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;

        let issues = issues_from_value(wrapper)?;

        let issue = issues.into_iter().find(|i| i.id == p.id).ok_or_else(|| {
            rmcp::ErrorData::invalid_params(
                format!("Issue '{}' not found in '{}'", p.id, p.path),
                None,
            )
        })?;

        let cmd = issue.verification.rerun_command.clone();
        let output = run_verification_command(&cmd, &p.path).await.map_err(|e| {
            rmcp::ErrorData::internal_error(format!("Verification command failed: {e}"), None)
        })?;

        let result = serde_json::json!({
            "verified": output.status.success(),
            "exit_code": output.status.code(),
            "stdout": String::from_utf8_lossy(&output.stdout),
            "stderr": String::from_utf8_lossy(&output.stderr),
            "rerun_command": cmd,
        });

        ok(&result)
    }

    // ── get_remaining_issues ──────────────────────────────────────────────────

    #[tool(
        description = "Get all issues that could not be fixed deterministically. \
        These are issues from issues-remaining.json — they need manual intervention or AI assistance. \
        Each issue includes full code evidence for AI-assisted fixing."
    )]
    async fn get_remaining_issues(
        &self,
        Parameters(p): Parameters<GetRemainingIssuesParams>,
    ) -> Result<CallToolResult, rmcp::ErrorData> {
        let dir = latest_report_dir(&p.path)
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;

        let wrapper: serde_json::Value = read_json(&dir.join("issues-remaining.json"))
            .map_err(|e| rmcp::ErrorData::internal_error(e.to_string(), None))?;

        let issues = issues_from_value(wrapper)?;
        ok(&issues)
    }
}

// ─── ServerHandler impl ───────────────────────────────────────────────────────

#[tool_handler]
impl ServerHandler for RGuardMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("rguard", env!("CARGO_PKG_VERSION")))
            .with_instructions(
                "Use scan_project first, then get_issues to retrieve findings with \
                pre-embedded code evidence. Use fix_issue or fix_all for deterministic fixes. \
                Use fix_preview for a dry-run. Use get_remaining_issues for issues that need \
                manual or AI-assisted intervention. Use verify_fix to confirm fixes worked.",
            )
    }
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/// Build and run the fixer engine with the given options.
async fn run_fixer(
    project_path: &str,
    category: Option<&str>,
    dry_run: bool,
    unsafe_fixes: bool,
    issue_ids: Option<Vec<String>>,
) -> anyhow::Result<rguard_core::fixer::FixReport> {
    use rguard_core::{
        config,
        fixer::{engine::FixerEngineConfig, FixerEngine, StageFilter},
        registry::{loader::load_fixer_descriptors, DescriptorRegistry},
    };

    let project_root = PathBuf::from(project_path);
    let config_path = project_root.join(".rguard.yaml");
    let cfg = config::load(&config_path)?;

    let fixer_descriptors = load_fixer_descriptors(&project_root)?;
    let reg = DescriptorRegistry::new(fixer_descriptors);
    let engine = FixerEngine::new(cfg, reg);

    let stage_filter = if let Some(cat) = category {
        // Map plural category names (from CLI conventions) to internal stage names
        let (fmt, lnt, sec, ast, dep, imp) = match cat {
            "formatters" | "format" => (true, false, false, false, false, false),
            "linters" | "lint" => (false, true, false, false, false, false),
            "security" => (false, false, true, false, false, false),
            "ast" => (false, false, false, true, false, false),
            "deps" => (false, false, false, false, true, false),
            "imports" | "import" => (false, false, false, false, false, true),
            _ => (false, false, false, false, false, false),
        };
        StageFilter::from_args(fmt, lnt, sec, ast, dep, imp)
    } else {
        StageFilter::from_args(false, false, false, false, false, false)
    };

    let reports_root = project_root.join("reports");
    let timestamp = epoch_timestamp();
    let output_dir = reports_root.join(&timestamp);
    let latest_dir = reports_root.join("latest");
    std::fs::create_dir_all(&output_dir)?;

    let engine_cfg = FixerEngineConfig {
        project_root,
        file_targets: vec![],
        stage_filter,
        dry_run,
        include_unsafe: unsafe_fixes,
        timeout_secs: None,
        output_dir,
        latest_dir,
        issue_ids,
    };

    engine.run(engine_cfg).await
}

/// Run a verification command in the project directory.
async fn run_verification_command(
    cmd: &str,
    project_path: &str,
) -> anyhow::Result<std::process::Output> {
    use tokio::process::Command;

    let mut parts = cmd.split_whitespace();
    let program = parts
        .next()
        .ok_or_else(|| anyhow::anyhow!("Empty command"))?;
    let args: Vec<&str> = parts.collect();

    let output = Command::new(program)
        .args(&args)
        .current_dir(project_path)
        .output()
        .await?;

    Ok(output)
}

/// Return seconds since UNIX epoch as a string, for use in directory names.
fn epoch_timestamp() -> String {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
        .to_string()
}
